version: "3.9"

services:
  lambda:
    container_name: local-lambda
    build: .
    ports:
      - "8000:8080"
  minio:
    image: quay.io/minio/minio:latest
    container_name: local-minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - "./minio:/data"
